.\" rpr - rich presence
.\" Copyright (C) 2022 ArcNyxx
.\" see LICENCE file for licensing information
.TH RPCLNT 1 rpclnt\-VERSION
.SH NAME
rpclnt \- rich presence setter
.SH SYNOPSIS
.SY rpclnt
.YS
.SH DESCRIPTION
.BR rpclnt (1)
sends rich presence data to a socket.
.SH FILES
.TP
.I SOCKET
Socket to send rich presence data.
.SH AUTHOR
Written by ArcNyxx.
.SH SEE ALSO
.BR rpserv (1),\  rpr (1)
