.\" rpr - rich presence
.\" Copyright (C) 2022 ArcNyxx
.\" see LICENCE file for licensing information
.TH RPSERV 1 rpserv\-VERSION
.SH NAME
rpserv \- rich presence daemon
.SH SYNOPSIS
.SY rpserv
.YS
.SH DESCRIPTION
.BR rpserv (1)
is a simple rich presence daemon for discord clients.
.BR rpserv (1)
sends rich presence data received by its socket to a discord client.
.SH FILES
.TP
.I SOCKET
Socket to receive rich presence data.
.SH AUTHOR
Written by ArcNyxx.
.SH SEE ALSO
.BR rpclnt (1),\  rpr (1)
